language: python
python:
  - "2.7"
  - "3.6"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov
  - pip install flake8
  - pip install radon
script:
  - cd tests
  - coverage run ./tests/tests.py
  - cd ..
  - codecov
  - flake8 --ignore=E501  # ignore "line too long errors"
  - radon cc ./pytescomobileirl/ -a 
  - radon mi .
  - radon raw . -s
