language: python
python:
  - "2.7"
  - "3.6"
  - "nightly"
install: #dependencies
  - pip install -r requirements.txt
  - pip install .
  - pip install codecov
# command to run tests
script:
  - coverage run ./tests/tests.py
  - codecov
